# Generated by Django 4.1.4 on 2023-01-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='name',
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsname',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
