# Generated by Django 4.1.4 on 2023-01-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_goods_name_goods_goodsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsname',
            field=models.CharField(max_length=100),
        ),
    ]
