# Generated by Django 4.1.4 on 2023-01-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_goods_goodsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goodsname',
            new_name='name',
        ),
    ]
