# Generated by Django 4.1.4 on 2023-01-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_goodsname_goods_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='name',
            new_name='name1',
        ),
    ]
