# Generated by Django 4.1.4 on 2023-01-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_name_goods_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='name1',
            new_name='name',
        ),
    ]
